language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
os:
  - linux
matrix:
    include:
        - os: osx
          language: generic
          env: TOXENV=py32
        - os: osx
          language: generic
          env: TOXENV=py33
        - os: osx
          language: generic
          env: TOXENV=py34
        - os: osx
          language: generic
          env: TOXENV=py35
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: py.test